name: medvisual
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  auto_route: ^9.2.2
  dio: ^5.7.0
  mime: ^2.0.0
  http_parser: ^4.0.2
  flutter_bloc: ^8.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  auto_route_generator: ^9.0.0
  flutter_dotenv: ^5.2.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/no_image_placeholder.jpg
    - .env
      